# ASSIGNEMENT NO.1
# ..50 NUMPY FUNCTIONS..

In [10]:
import numpy as np   ## .func no.(1)
np.pi

3.141592653589793

In [12]:
np.sin      ## func no..(2)

<ufunc 'sin'>

In [13]:
np.cos    ## func no..(3)

<ufunc 'cos'>

In [14]:
np.sin(90)    ## .func no.(4)

0.8939966636005579

In [15]:
np.cos(90)         ## .func no.(5)

-0.4480736161291701

In [16]:
l1 = [1,2,3]
l2 = [4,5,6]
l1+l2

[1, 2, 3, 4, 5, 6]

In [18]:
# array()
array1 = np.array(l1)     ## .func no..(6)
array1

array([1, 2, 3])

In [19]:
array2 = np.array(l2)
array2

array([4, 5, 6])

In [20]:
array3 = array1 + array2
array3

array([5, 7, 9])

In [30]:
array4 = np.array([[10,20,30]])
print(array4[0,1])
print(array4[0,0])
print(array4[0])

20
10
[10 20 30]


In [31]:
array4.shape      ## .func no.(7)

(1, 3)

In [32]:
array4.dtype        ## func no..(8)

dtype('int64')

In [33]:
array4[0,1] = 25      ## .func no.(9)
array4

array([[10, 25, 30]])

# Array creation : conversion from other python structures

In [34]:
listarray = np.array([[1,2,3],[4,5,6],[7,8,9]])   ## func no..(10)
listarray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [35]:
listarray.size      ## .func no.(11)

9

In [36]:
np.array({2,3,5})     ## func no..(12)

array({2, 3, 5}, dtype=object)

In [37]:
zeros = np.zeros((2,5))     ## .func no.(13)
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [38]:
rng = np.arange(15)           ## func no..(14)
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [40]:
lspace = np.linspace(1,4,4)          ## func no..(15)
lspace

array([1., 2., 3., 4.])

In [41]:
emp = np.empty((4,6))    ## .func no.(16)
emp

array([[4.65374633e-310, 6.94330673e-310, 6.94330674e-310,
        6.94330674e-310, 6.94330673e-310, 6.94330674e-310],
       [6.94330674e-310, 6.94330674e-310, 6.94330674e-310,
        6.94332376e-310, 6.94330673e-310, 6.94330674e-310],
       [6.94330674e-310, 6.94330673e-310, 6.94330674e-310,
        6.94330674e-310, 6.94330674e-310, 6.94330674e-310],
       [6.94332376e-310, 6.94330673e-310, 6.94330674e-310,
        6.94330674e-310, 6.94330673e-310, 6.94332511e-310]])

In [43]:
emp_like = np.empty_like(lspace)  ## func no..(17)
emp_like

array([1., 2., 3., 4.])

In [44]:
ide = np.identity(45)       ## func no..(18)
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [45]:
ide.shape        ## .func no.(19)

(45, 45)

In [46]:
arr = np.arange(99)        ## .func no..(20)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [48]:
arr.reshape(3,33)         ##.func no..(21)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [49]:
arr = arr.ravel()     ##.func no..(22)


In [50]:
arr.shape

(99,)

In [51]:
x = [[1,2,3],[4,5,6],[7,1,0]]

In [52]:
ar = np.array(x)

In [53]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [54]:
ar.sum(axis=0)        ## func no..(23)

array([12,  8,  9])

In [55]:
ar.sum(axis=1)

array([ 6, 15,  8])

In [56]:
ar.T                         ## func no...(24)

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [57]:
ar.flat              ##func no ..(25)

In [58]:
for item in ar.flat:            ##func no....(26)
    print(item)

1
2
3
4
5
6
7
1
0


In [59]:
ar.ndim                          ##func no..(27)

2

In [60]:
ar.nbytes               ## func no.(28)

72

In [61]:
one = np.array([1,3,4,634,2])
one.argmax()               ## func no.(29)

3

In [62]:
one.argmin()              ## func no.(30)

0

In [63]:
one.argsort()              ## func no.(31)

array([0, 4, 1, 2, 3])

In [64]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [65]:
ar2 = np.array([[1,2,1],
               [4,0,6],
               [8,1,0]])

In [66]:
ar + ar2                   ## func no.(32)

array([[ 2,  4,  4],
       [ 8,  5, 12],
       [15,  2,  0]])

In [67]:
ar * ar2            ## func no.(33)

array([[ 1,  4,  3],
       [16,  0, 36],
       [56,  1,  0]])

In [68]:
np.sqrt(ar)        ## func no.(34)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

In [69]:
ar.sum()      ## func no.(35)

29

In [71]:
ar.min()   ## func no.(36)

0

In [72]:
ar.max()       ## func no.(37)

7

In [73]:
np.where(ar>5)      ## func no.(38)

(array([1, 2]), array([2, 0]))

In [74]:
type(np.where(ar>5))   ## func no.(39)

tuple

In [75]:
np.count_nonzero(ar)     ## func no.(40)

8

In [76]:
np.nonzero(ar)      ## func no.(41)

(array([0, 0, 0, 1, 1, 1, 2, 2]), array([0, 1, 2, 0, 1, 2, 0, 1]))

In [77]:
one.tolist()         ## func no.(42)

[1, 3, 4, 634, 2]

# hyperbolic functions

In [2]:
import numpy as np
import math
in_array = [0, math.pi / 2, np.pi / 3, np.pi]
print ("Input array : \n", in_array)
Sinh_Values = np.sinh(in_array)          ## func no.(43)
print ("\nSine Hyperbolic values : \n", Sinh_Values)

Input array : 
 [0, 1.5707963267948966, 1.0471975511965976, 3.141592653589793]

Sine Hyperbolic values : 
 [ 0.          2.3012989   1.24936705 11.54873936]


In [3]:
 
in_array = [0, math.pi / 2, np.pi / 3, np.pi]
print ("Input array : \n", in_array)
 
cosh_Values = np.cosh(in_array)       ## func no.(44)
print ("\ncosine Hyperbolic values : \n", cosh_Values)

Input array : 
 [0, 1.5707963267948966, 1.0471975511965976, 3.141592653589793]

cosine Hyperbolic values : 
 [ 1.          2.50917848  1.60028686 11.59195328]


In [4]:

# around() function                                  func no.(45)
 
in_array = [.5, 1.5, 2.5, 3.5, 4.5, 10.1]
print ("Input array : \n", in_array)
 
round_off_values = np.around(in_array)
print ("\nRounded values : \n", round_off_values)
 
 
in_array = [.53, 1.54, .71]
print ("\nInput array : \n", in_array)
 
round_off_values = np.around(in_array)
print ("\nRounded values : \n", round_off_values)

Input array : 
 [0.5, 1.5, 2.5, 3.5, 4.5, 10.1]

Rounded values : 
 [ 0.  2.  2.  4.  4. 10.]

Input array : 
 [0.53, 1.54, 0.71]

Rounded values : 
 [1. 2. 1.]


In [6]:
# round_() fun                                     func no.(46)
in_array = [.5, 1.5, 2.5, 3.5, 4.5, 10.1]
print ("Input array : \n", in_array)
 
round_off_values = np.round_(in_array)
print ("\nRounded values : \n", round_off_values)
 
 
in_array = [.53, 1.54, .71]
print ("\nInput array : \n", in_array)
 
round_off_values = np.round_(in_array)
print ("\nRounded values : \n", round_off_values)
 
in_array = [.5538, 1.33354, .71445]
print ("\nInput array : \n", in_array)
 
round_off_values = np.round_(in_array, decimals = 3)
print ("\nRounded values : \n", round_off_values)

Input array : 
 [0.5, 1.5, 2.5, 3.5, 4.5, 10.1]

Rounded values : 
 [ 0.  2.  2.  4.  4. 10.]

Input array : 
 [0.53, 1.54, 0.71]

Rounded values : 
 [1. 2. 1.]

Input array : 
 [0.5538, 1.33354, 0.71445]

Rounded values : 
 [0.554 1.334 0.714]


In [7]:

# exp() function               ## func no.(47)
import numpy as np
 
in_array = [1, 3, 5]
print ("Input array : ", in_array)
 
out_array = np.exp(in_array)
print ("Output array : ", out_array)

Input array :  [1, 3, 5]
Output array :  [  2.71828183  20.08553692 148.4131591 ]


In [8]:

# log() function       ## func no.(48)
 
in_array = [1, 3, 5, 2**8]
print ("Input array : ", in_array)
 
out_array = np.log(in_array)
print ("Output array : ", out_array)
 
 
print("\nnp.log(4**4) : ", np.log(4**4))
print("np.log(2**8) : ", np.log(2**8))

Input array :  [1, 3, 5, 256]
Output array :  [0.         1.09861229 1.60943791 5.54517744]

np.log(4**4) :  5.545177444479562
np.log(2**8) :  5.545177444479562


In [9]:
#reciprocal() func         ##..(49)
in_num = 2.0
print ("Input  number : ", in_num)
 
out_num = np.reciprocal(in_num)
print ("Output number : ", out_num)

Input  number :  2.0
Output number :  0.5


In [10]:
# divide() function   ## func no.(50)
 
# input_array
arr1 = [2, 27, 2, 21, 23]
arr2 = [2, 3, 4, 5, 6]
print ("arr1         : ", arr1)
print ("arr2         : ", arr2)
 
# output_array
out = np.divide(arr1, arr2)
print ("\nOutput array : \n", out)

arr1         :  [2, 27, 2, 21, 23]
arr2         :  [2, 3, 4, 5, 6]

Output array : 
 [1.         9.         0.5        4.2        3.83333333]


# ......END......